apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-todo
  name: backend-todo
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 8100
  selector:
    service: backend-todo