apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-todo
  name: backend-todo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-todo
    spec:
      containers:
      - image: programmingwebsite/restapi-todo
        name: backend-todo
        ports:
          - containerPort: 8100          
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
        env:
        - name: USERS_TODO_TABLE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: USERS_TODO_TABLE
        - name: USERID_INDEX
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: USERID_INDEX
        - name: TODOS_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: TODOS_S3_BUCKET
        - name: THUMBNAILS_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: THUMBNAILS_S3_BUCKET
        - name: SIGNED_URL_EXPIRATION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: SIGNED_URL_EXPIRATION
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_PROFILE 
        - name: TODO_VERSION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: TODO_VERSION 
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL  
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true                                                                   
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret           